# syntax=docker/dockerfile:1
FROM golang:1.19

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY app/go.mod app/go.sum ./
RUN go mod download

# Copy the source code
COPY app/*.go ./

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /ig2tg

# Run
CMD ["/ig2tg"]
